name: CI
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  validate:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Validate with Windows PowerShell 5.1
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          Install-Module Pester -RequiredVersion '5.7.1' -Repository PSGallery -Scope CurrentUser -Force
          Install-Module PSScriptAnalyzer -RequiredVersion '1.25.0' -Repository PSGallery -Scope CurrentUser -Force
          Import-Module Pester -RequiredVersion '5.7.1' -Force
          Import-Module PSScriptAnalyzer -RequiredVersion '1.25.0' -Force
          .\build\Invoke-Validation.ps1
